name: NoAllayReplication
version: '${project.version}'
main: be.achent.noallayreplication.NoAllayReplication
api-version: 1.20
author: Achent
description: Prevent Allay Replication
commands:
  noallayreplication:
    description: Commande principale du plugin
    aliases: nar
permissions:
  noallayreplication.*:
    description: Donne toutes les permissions du plugin
    children:
      noallayreplication.help: true
      noallayreplication.reload: true
  noallayreplication.help:
    description: Donne la permission d'afficher les commandes du plugin
    default: op
  noallayreplication.reload:
    description: Donne la permission de recharger le fichier de config
    default: op